// <auto-generated />
using System;
using AppCore.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppCore.Data.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200202040634_create002")]
    partial class create002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppCore.Data.Entities.System.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrowserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImpersonatorTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImpersonatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys001", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anhdaidien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMTND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capbac")
                        .HasColumnType("int");

                    b.Property<string>("Chucvu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hovaten")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Kieuuser")
                        .HasColumnType("int");

                    b.Property<string>("Manhanvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ngaysinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Sodienthoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("093d68c9-d02f-457a-b62f-0f067dcf4fcc"),
                            Capbac = 0,
                            Hovaten = "Admin",
                            Kieuuser = 0,
                            Manhanvien = "890801",
                            Ngaysinh = "2020-02-02 11:06",
                            Ngaytao = new DateTime(2020, 2, 2, 11, 6, 33, 856, DateTimeKind.Local).AddTicks(1657),
                            Password = "duytuit89!",
                            Trangthai = 0
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys002", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kieunhom")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tennhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NhomKys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73df7fbf-15af-4e3d-a4b9-9a4e107e8586"),
                            Kieunhom = 1,
                            Ngaytao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tennhom = "Quản trị",
                            Thutu = 0,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys003", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Danhmucid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kieutrinhky")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tendanhmuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tennhomky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Danhmucid");

                    b.HasIndex("Nhomky_id");

                    b.ToTable("TrinhKys");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys004", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Hoanthanh")
                        .HasColumnType("int");

                    b.Property<string>("Namegroup")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Tongnhomky")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys005", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Madanhmuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tendanhmuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .HasColumnType("int");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f65afc49-fd8d-4d98-8969-bc6cbc7b8e5c"),
                            Madanhmuc = "DM01",
                            Tendanhmuc = "Quản Trị",
                            Thutu = 1,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys006", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Capdo")
                        .HasColumnType("int");

                    b.Property<Guid>("Danhmucid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Duongdan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idcha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Macode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenmenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .HasColumnType("int");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Danhmucid");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = "ht01",
                            Capdo = 1,
                            Danhmucid = new Guid("f65afc49-fd8d-4d98-8969-bc6cbc7b8e5c"),
                            Duongdan = "thongtin",
                            Tenmenu = "Quản trị",
                            Thutu = 1,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht02",
                            Capdo = 3,
                            Danhmucid = new Guid("f65afc49-fd8d-4d98-8969-bc6cbc7b8e5c"),
                            Duongdan = "menu",
                            Idcha = "ht01",
                            Tenmenu = "Menu",
                            Thutu = 2,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht03",
                            Capdo = 3,
                            Danhmucid = new Guid("f65afc49-fd8d-4d98-8969-bc6cbc7b8e5c"),
                            Duongdan = "danhmuc",
                            Idcha = "ht01",
                            Tenmenu = "Danh mục",
                            Thutu = 3,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht04",
                            Capdo = 3,
                            Danhmucid = new Guid("f65afc49-fd8d-4d98-8969-bc6cbc7b8e5c"),
                            Duongdan = "nhomky",
                            Idcha = "ht01",
                            Tenmenu = "Nhóm ký",
                            Thutu = 4,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht05",
                            Capdo = 3,
                            Danhmucid = new Guid("f65afc49-fd8d-4d98-8969-bc6cbc7b8e5c"),
                            Duongdan = "trinhky",
                            Idcha = "ht01",
                            Tenmenu = "Trình ký",
                            Thutu = 5,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht06",
                            Capdo = 3,
                            Danhmucid = new Guid("f65afc49-fd8d-4d98-8969-bc6cbc7b8e5c"),
                            Duongdan = "phanquyen",
                            Idcha = "ht01",
                            Tenmenu = "Phân quyền",
                            Thutu = 6,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht07",
                            Capdo = 3,
                            Danhmucid = new Guid("f65afc49-fd8d-4d98-8969-bc6cbc7b8e5c"),
                            Duongdan = "usernhom",
                            Idcha = "ht01",
                            Tenmenu = "User - nhóm",
                            Thutu = 7,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys007", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Dahuy")
                        .HasColumnType("bit");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Kieutrinhky")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Sys003Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<Guid>("Trinhky_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Groupid");

                    b.HasIndex("Sys003Id");

                    b.ToTable("QuyTrinhs");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys008", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Menuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("quyenCapNhap")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenThem")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenXem")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenXoa")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Menuid");

                    b.HasIndex("Nhomky_id");

                    b.ToTable("PhanQuyens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df32a9e5-ed11-48a3-a7d6-f8e16198d2d0"),
                            Menuid = "ht01",
                            Nhomky_id = new Guid("73df7fbf-15af-4e3d-a4b9-9a4e107e8586"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("013d2c92-b78f-43d8-9220-ace94411288b"),
                            Menuid = "ht02",
                            Nhomky_id = new Guid("73df7fbf-15af-4e3d-a4b9-9a4e107e8586"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("779963f9-e9b1-41ba-a05b-65d054838918"),
                            Menuid = "ht03",
                            Nhomky_id = new Guid("73df7fbf-15af-4e3d-a4b9-9a4e107e8586"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("c66759c2-1070-4dc6-8e3d-2f1f4a6ec02f"),
                            Menuid = "ht04",
                            Nhomky_id = new Guid("73df7fbf-15af-4e3d-a4b9-9a4e107e8586"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("24a6c212-c316-4fcd-ad11-d1db9eba81bc"),
                            Menuid = "ht05",
                            Nhomky_id = new Guid("73df7fbf-15af-4e3d-a4b9-9a4e107e8586"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("0c3b6db7-06a8-4292-ae72-46587f57789f"),
                            Menuid = "ht06",
                            Nhomky_id = new Guid("73df7fbf-15af-4e3d-a4b9-9a4e107e8586"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("09a4765f-611a-42fc-acad-f42e48348d2e"),
                            Menuid = "ht07",
                            Nhomky_id = new Guid("73df7fbf-15af-4e3d-a4b9-9a4e107e8586"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys009", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manhanvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tennhomky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nhomky_id");

                    b.HasIndex("UserID");

                    b.ToTable("UserNhomKy");

                    b.HasData(
                        new
                        {
                            Id = new Guid("edc08678-09f6-4de6-ad41-a1daaa5e3ce2"),
                            Manhanvien = "890801",
                            Nhomky_id = new Guid("73df7fbf-15af-4e3d-a4b9-9a4e107e8586"),
                            Tennhomky = "Quản trị",
                            Thutu = 0,
                            Trangthai = 1,
                            UserID = new Guid("093d68c9-d02f-457a-b62f-0f067dcf4fcc"),
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Timer", b =>
                {
                    b.Property<int>("Timerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Thoigiandangxuat")
                        .HasColumnType("int");

                    b.Property<byte>("Trangthai")
                        .HasColumnType("tinyint");

                    b.HasKey("Timerid");

                    b.ToTable("Timers");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys003", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys005", "Sys005")
                        .WithMany("Sys003")
                        .HasForeignKey("Danhmucid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys003")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys006", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys005", "Sys005")
                        .WithMany("Sys006")
                        .HasForeignKey("Danhmucid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys007", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys004", "Sys004")
                        .WithMany("Sys007")
                        .HasForeignKey("Groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys003", "Sys003")
                        .WithMany()
                        .HasForeignKey("Sys003Id");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys008", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys006", "Sys006")
                        .WithMany("Sys008")
                        .HasForeignKey("Menuid");

                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys008")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys009", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys009")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys001", "Sys001")
                        .WithMany("Sys009")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
