// <auto-generated />
using System;
using AppCore.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppCore.Data.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200216010056_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppCore.Data.Entities.System.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrowserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImpersonatorTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImpersonatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys001", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anhdaidien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMTND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capbac")
                        .HasColumnType("int");

                    b.Property<string>("Chucvu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hovaten")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Kieuuser")
                        .HasColumnType("int");

                    b.Property<string>("Manhanvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ngaysinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Sodienthoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccc32c6-31ff-4f39-b55a-67b4c75bc3c8"),
                            Capbac = 0,
                            Hovaten = "Admin",
                            Kieuuser = 0,
                            Manhanvien = "890801",
                            Ngaysinh = "2020-02-16 08:00",
                            Ngaytao = new DateTime(2020, 2, 16, 8, 0, 55, 615, DateTimeKind.Local).AddTicks(6524),
                            Password = "duytuit89!",
                            Trangthai = 0
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys002", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kieunhom")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tennhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NhomKys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("17b888f2-12d8-4cae-9fe3-7c0d53f157c4"),
                            Kieunhom = 1,
                            Ngaytao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tennhom = "Quản trị",
                            Thutu = 0,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys003", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Danhmucid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kieutrinhky")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tendanhmuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tennhomky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Danhmucid");

                    b.HasIndex("Nhomky_id");

                    b.ToTable("TrinhKys");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys004", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Hoanthanh")
                        .HasColumnType("int");

                    b.Property<string>("Namegroup")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Tongnhomky")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys005", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Madanhmuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tendanhmuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .HasColumnType("int");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a9d6d08-d27a-47ee-9871-440e4b552ecb"),
                            Madanhmuc = "DM01",
                            Tendanhmuc = "Quản Trị",
                            Thutu = 1,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys006", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Capdo")
                        .HasColumnType("int");

                    b.Property<Guid>("Danhmucid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Duongdan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idcha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Macode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenmenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .HasColumnType("int");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Danhmucid");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = "ht01",
                            Capdo = 1,
                            Danhmucid = new Guid("4a9d6d08-d27a-47ee-9871-440e4b552ecb"),
                            Duongdan = "thongtin",
                            Tenmenu = "Quản trị",
                            Thutu = 1,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht02",
                            Capdo = 3,
                            Danhmucid = new Guid("4a9d6d08-d27a-47ee-9871-440e4b552ecb"),
                            Duongdan = "menu",
                            Idcha = "ht01",
                            Tenmenu = "Menu",
                            Thutu = 2,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht03",
                            Capdo = 3,
                            Danhmucid = new Guid("4a9d6d08-d27a-47ee-9871-440e4b552ecb"),
                            Duongdan = "danhmuc",
                            Idcha = "ht01",
                            Tenmenu = "Danh mục",
                            Thutu = 3,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht04",
                            Capdo = 3,
                            Danhmucid = new Guid("4a9d6d08-d27a-47ee-9871-440e4b552ecb"),
                            Duongdan = "nhomky",
                            Idcha = "ht01",
                            Tenmenu = "Nhóm ký",
                            Thutu = 4,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht05",
                            Capdo = 3,
                            Danhmucid = new Guid("4a9d6d08-d27a-47ee-9871-440e4b552ecb"),
                            Duongdan = "trinhky",
                            Idcha = "ht01",
                            Tenmenu = "Trình ký",
                            Thutu = 5,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht06",
                            Capdo = 3,
                            Danhmucid = new Guid("4a9d6d08-d27a-47ee-9871-440e4b552ecb"),
                            Duongdan = "phanquyen",
                            Idcha = "ht01",
                            Tenmenu = "Phân quyền",
                            Thutu = 6,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht07",
                            Capdo = 3,
                            Danhmucid = new Guid("4a9d6d08-d27a-47ee-9871-440e4b552ecb"),
                            Duongdan = "usernhom",
                            Idcha = "ht01",
                            Tenmenu = "User - nhóm",
                            Thutu = 7,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys007", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Dahuy")
                        .HasColumnType("bit");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Kieutrinhky")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Sys003Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<Guid>("Trinhky_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Groupid");

                    b.HasIndex("Sys003Id");

                    b.ToTable("QuyTrinhs");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys008", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Menuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("quyenCapNhap")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenThem")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenXem")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenXoa")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Menuid");

                    b.HasIndex("Nhomky_id");

                    b.ToTable("PhanQuyens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ea0c011b-c2a7-4ce3-b525-28cad80eecca"),
                            Menuid = "ht01",
                            Nhomky_id = new Guid("17b888f2-12d8-4cae-9fe3-7c0d53f157c4"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("88a1ca5d-3035-48f5-bd17-1e36bde16cfa"),
                            Menuid = "ht02",
                            Nhomky_id = new Guid("17b888f2-12d8-4cae-9fe3-7c0d53f157c4"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("2bcde03e-ceb3-4516-b2b7-91f52c9da0da"),
                            Menuid = "ht03",
                            Nhomky_id = new Guid("17b888f2-12d8-4cae-9fe3-7c0d53f157c4"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("2e80f950-4569-4456-88ad-94074779dbce"),
                            Menuid = "ht04",
                            Nhomky_id = new Guid("17b888f2-12d8-4cae-9fe3-7c0d53f157c4"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("b6b0da13-b226-438b-847b-3344e59d9277"),
                            Menuid = "ht05",
                            Nhomky_id = new Guid("17b888f2-12d8-4cae-9fe3-7c0d53f157c4"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("898554f7-5fde-4f73-a87c-35146f27969c"),
                            Menuid = "ht06",
                            Nhomky_id = new Guid("17b888f2-12d8-4cae-9fe3-7c0d53f157c4"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("fc5e5eee-07c2-4ef9-a1e3-588ff19bf91e"),
                            Menuid = "ht07",
                            Nhomky_id = new Guid("17b888f2-12d8-4cae-9fe3-7c0d53f157c4"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys009", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manhanvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tennhomky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nhomky_id");

                    b.HasIndex("UserID");

                    b.ToTable("UserNhomKy");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cd684742-e4d7-4eba-99a6-f950ad003c2a"),
                            Manhanvien = "890801",
                            Nhomky_id = new Guid("17b888f2-12d8-4cae-9fe3-7c0d53f157c4"),
                            Tennhomky = "Quản trị",
                            Thutu = 0,
                            Trangthai = 1,
                            UserID = new Guid("cccc32c6-31ff-4f39-b55a-67b4c75bc3c8"),
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Timer", b =>
                {
                    b.Property<int>("Timerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Thoigiandangxuat")
                        .HasColumnType("int");

                    b.Property<byte>("Trangthai")
                        .HasColumnType("tinyint");

                    b.HasKey("Timerid");

                    b.ToTable("Timers");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys003", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys005", "Sys005")
                        .WithMany("Sys003")
                        .HasForeignKey("Danhmucid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys003")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys006", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys005", "Sys005")
                        .WithMany("Sys006")
                        .HasForeignKey("Danhmucid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys007", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys004", "Sys004")
                        .WithMany("Sys007")
                        .HasForeignKey("Groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys003", "Sys003")
                        .WithMany()
                        .HasForeignKey("Sys003Id");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys008", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys006", "Sys006")
                        .WithMany("Sys008")
                        .HasForeignKey("Menuid");

                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys008")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys009", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys009")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys001", "Sys001")
                        .WithMany("Sys009")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
