// <auto-generated />
using System;
using AppCore.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppCore.Data.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200206072944_update001")]
    partial class update001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppCore.Data.Entities.System.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrowserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImpersonatorTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImpersonatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys001", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anhdaidien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMTND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capbac")
                        .HasColumnType("int");

                    b.Property<string>("Chucvu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hovaten")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Kieuuser")
                        .HasColumnType("int");

                    b.Property<string>("Manhanvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Sodienthoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4ae7fea-d230-4a1d-8e26-9baebbd90891"),
                            Capbac = 0,
                            Hovaten = "Admin",
                            Kieuuser = 0,
                            Manhanvien = "890801",
                            Ngaysinh = new DateTime(2020, 2, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            Ngaytao = new DateTime(2020, 2, 6, 14, 29, 44, 536, DateTimeKind.Local).AddTicks(7840),
                            Password = "duytuit89!",
                            Trangthai = 0
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys002", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kieunhom")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tennhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NhomKys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68b68eab-e8f3-4aed-85ca-407139aebda9"),
                            Kieunhom = 1,
                            Ngaytao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tennhom = "Quản trị",
                            Thutu = 0,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys003", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Danhmucid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kieutrinhky")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tendanhmuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tennhomky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Danhmucid");

                    b.HasIndex("Nhomky_id");

                    b.ToTable("TrinhKys");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys004", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Hoanthanh")
                        .HasColumnType("int");

                    b.Property<string>("Namegroup")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Tongnhomky")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys005", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Madanhmuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tendanhmuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .HasColumnType("int");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8909fd2a-7402-479e-af7b-c35e7e7aace3"),
                            Madanhmuc = "DM01",
                            Tendanhmuc = "Quản Trị",
                            Thutu = 1,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys006", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Capdo")
                        .HasColumnType("int");

                    b.Property<Guid>("Danhmucid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Duongdan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idcha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Macode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenmenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .HasColumnType("int");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Danhmucid");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = "ht01",
                            Capdo = 1,
                            Danhmucid = new Guid("8909fd2a-7402-479e-af7b-c35e7e7aace3"),
                            Duongdan = "thongtin",
                            Tenmenu = "Quản trị",
                            Thutu = 1,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht02",
                            Capdo = 3,
                            Danhmucid = new Guid("8909fd2a-7402-479e-af7b-c35e7e7aace3"),
                            Duongdan = "menu",
                            Idcha = "ht01",
                            Tenmenu = "Menu",
                            Thutu = 2,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht03",
                            Capdo = 3,
                            Danhmucid = new Guid("8909fd2a-7402-479e-af7b-c35e7e7aace3"),
                            Duongdan = "danhmuc",
                            Idcha = "ht01",
                            Tenmenu = "Danh mục",
                            Thutu = 3,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht04",
                            Capdo = 3,
                            Danhmucid = new Guid("8909fd2a-7402-479e-af7b-c35e7e7aace3"),
                            Duongdan = "nhomky",
                            Idcha = "ht01",
                            Tenmenu = "Nhóm ký",
                            Thutu = 4,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht05",
                            Capdo = 3,
                            Danhmucid = new Guid("8909fd2a-7402-479e-af7b-c35e7e7aace3"),
                            Duongdan = "trinhky",
                            Idcha = "ht01",
                            Tenmenu = "Trình ký",
                            Thutu = 5,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht06",
                            Capdo = 3,
                            Danhmucid = new Guid("8909fd2a-7402-479e-af7b-c35e7e7aace3"),
                            Duongdan = "phanquyen",
                            Idcha = "ht01",
                            Tenmenu = "Phân quyền",
                            Thutu = 6,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht07",
                            Capdo = 3,
                            Danhmucid = new Guid("8909fd2a-7402-479e-af7b-c35e7e7aace3"),
                            Duongdan = "usernhom",
                            Idcha = "ht01",
                            Tenmenu = "User - nhóm",
                            Thutu = 7,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys007", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Dahuy")
                        .HasColumnType("bit");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Kieutrinhky")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Sys003Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<Guid>("Trinhky_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Groupid");

                    b.HasIndex("Sys003Id");

                    b.ToTable("QuyTrinhs");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys008", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Menuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("quyenCapNhap")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenThem")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenXem")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenXoa")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Menuid");

                    b.HasIndex("Nhomky_id");

                    b.ToTable("PhanQuyens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("169c47b6-4a53-4cc2-b339-84d7907290e5"),
                            Menuid = "ht01",
                            Nhomky_id = new Guid("68b68eab-e8f3-4aed-85ca-407139aebda9"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("342a9e9a-4788-4356-98c8-45654e007f42"),
                            Menuid = "ht02",
                            Nhomky_id = new Guid("68b68eab-e8f3-4aed-85ca-407139aebda9"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("164cf6c1-92b7-4a02-8e36-1b5cec5e8090"),
                            Menuid = "ht03",
                            Nhomky_id = new Guid("68b68eab-e8f3-4aed-85ca-407139aebda9"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("65eed04f-2e47-498a-8115-f8a598a799a9"),
                            Menuid = "ht04",
                            Nhomky_id = new Guid("68b68eab-e8f3-4aed-85ca-407139aebda9"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("2674daa3-e47a-471d-ac6c-5c889505b0ad"),
                            Menuid = "ht05",
                            Nhomky_id = new Guid("68b68eab-e8f3-4aed-85ca-407139aebda9"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("3057f235-a57b-455c-bc9d-65a1937a746c"),
                            Menuid = "ht06",
                            Nhomky_id = new Guid("68b68eab-e8f3-4aed-85ca-407139aebda9"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("9dfec5ee-ce9c-4ab4-8e83-5329f6c68b3d"),
                            Menuid = "ht07",
                            Nhomky_id = new Guid("68b68eab-e8f3-4aed-85ca-407139aebda9"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys009", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manhanvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tennhomky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nhomky_id");

                    b.HasIndex("UserID");

                    b.ToTable("UserNhomKy");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2600c003-a372-43ec-8c35-8469cc3e5b76"),
                            Manhanvien = "890801",
                            Nhomky_id = new Guid("68b68eab-e8f3-4aed-85ca-407139aebda9"),
                            Tennhomky = "Quản trị",
                            Thutu = 0,
                            Trangthai = 1,
                            UserID = new Guid("a4ae7fea-d230-4a1d-8e26-9baebbd90891"),
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Timer", b =>
                {
                    b.Property<int>("Timerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Thoigiandangxuat")
                        .HasColumnType("int");

                    b.Property<byte>("Trangthai")
                        .HasColumnType("tinyint");

                    b.HasKey("Timerid");

                    b.ToTable("Timers");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys003", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys005", "Sys005")
                        .WithMany("Sys003")
                        .HasForeignKey("Danhmucid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys003")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys006", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys005", "Sys005")
                        .WithMany("Sys006")
                        .HasForeignKey("Danhmucid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys007", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys004", "Sys004")
                        .WithMany("Sys007")
                        .HasForeignKey("Groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys003", "Sys003")
                        .WithMany()
                        .HasForeignKey("Sys003Id");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys008", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys006", "Sys006")
                        .WithMany("Sys008")
                        .HasForeignKey("Menuid");

                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys008")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys009", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys009")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys001", "Sys001")
                        .WithMany("Sys009")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
