// <auto-generated />
using System;
using AppCore.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppCore.Data.EF.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AppCore.Data.Entities.System.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrowserInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionDuration")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExecutionTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImpersonatorTenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ImpersonatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameters")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys001", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anhdaidien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CMTND")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capbac")
                        .HasColumnType("int");

                    b.Property<string>("Chucvu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hovaten")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Kieuuser")
                        .HasColumnType("int");

                    b.Property<string>("Manhanvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ngaysinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Sodienthoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41ab7842-584d-4da5-9b38-64d71b0978cd"),
                            Capbac = 0,
                            Hovaten = "Admin",
                            Kieuuser = 0,
                            Manhanvien = "890801",
                            Ngaysinh = "2020-02-05 10:09",
                            Ngaytao = new DateTime(2020, 2, 5, 10, 9, 59, 373, DateTimeKind.Local).AddTicks(2937),
                            Password = "duytuit89!",
                            Trangthai = 0
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys002", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kieunhom")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tennhom")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NhomKys");

                    b.HasData(
                        new
                        {
                            Id = new Guid("543d485d-8810-406c-9438-9fded201eeeb"),
                            Kieunhom = 1,
                            Ngaytao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Tennhom = "Quản trị",
                            Thutu = 0,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys003", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Danhmucid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kieutrinhky")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tendanhmuc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tennhomky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Danhmucid");

                    b.HasIndex("Nhomky_id");

                    b.ToTable("TrinhKys");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys004", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Hoanthanh")
                        .HasColumnType("int");

                    b.Property<string>("Namegroup")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Tongnhomky")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys005", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Madanhmuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tendanhmuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .HasColumnType("int");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("42492c16-e237-47a1-b733-6b055aedc641"),
                            Madanhmuc = "DM01",
                            Tendanhmuc = "Quản Trị",
                            Thutu = 1,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys006", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Capdo")
                        .HasColumnType("int");

                    b.Property<Guid>("Danhmucid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Duongdan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idcha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Macode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tenmenu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .HasColumnType("int");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Danhmucid");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = "ht01",
                            Capdo = 1,
                            Danhmucid = new Guid("42492c16-e237-47a1-b733-6b055aedc641"),
                            Duongdan = "thongtin",
                            Tenmenu = "Quản trị",
                            Thutu = 1,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht02",
                            Capdo = 3,
                            Danhmucid = new Guid("42492c16-e237-47a1-b733-6b055aedc641"),
                            Duongdan = "menu",
                            Idcha = "ht01",
                            Tenmenu = "Menu",
                            Thutu = 2,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht03",
                            Capdo = 3,
                            Danhmucid = new Guid("42492c16-e237-47a1-b733-6b055aedc641"),
                            Duongdan = "danhmuc",
                            Idcha = "ht01",
                            Tenmenu = "Danh mục",
                            Thutu = 3,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht04",
                            Capdo = 3,
                            Danhmucid = new Guid("42492c16-e237-47a1-b733-6b055aedc641"),
                            Duongdan = "nhomky",
                            Idcha = "ht01",
                            Tenmenu = "Nhóm ký",
                            Thutu = 4,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht05",
                            Capdo = 3,
                            Danhmucid = new Guid("42492c16-e237-47a1-b733-6b055aedc641"),
                            Duongdan = "trinhky",
                            Idcha = "ht01",
                            Tenmenu = "Trình ký",
                            Thutu = 5,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht06",
                            Capdo = 3,
                            Danhmucid = new Guid("42492c16-e237-47a1-b733-6b055aedc641"),
                            Duongdan = "phanquyen",
                            Idcha = "ht01",
                            Tenmenu = "Phân quyền",
                            Thutu = 6,
                            Trangthai = 1
                        },
                        new
                        {
                            Id = "ht07",
                            Capdo = 3,
                            Danhmucid = new Guid("42492c16-e237-47a1-b733-6b055aedc641"),
                            Duongdan = "usernhom",
                            Idcha = "ht01",
                            Tenmenu = "User - nhóm",
                            Thutu = 7,
                            Trangthai = 1
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys007", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Dahuy")
                        .HasColumnType("bit");

                    b.Property<string>("Ghichu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Groupid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Kieutrinhky")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Ngaycapnhap")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Ngayhuy")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Ngaytao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nguoitao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nguoitaoid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("Sys003Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<Guid>("Trinhky_id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Groupid");

                    b.HasIndex("Sys003Id");

                    b.ToTable("QuyTrinhs");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys008", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Menuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("quyenCapNhap")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenThem")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenXem")
                        .HasColumnType("bit");

                    b.Property<bool>("quyenXoa")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Menuid");

                    b.HasIndex("Nhomky_id");

                    b.ToTable("PhanQuyens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a474aeb-48ab-4eb5-b1aa-6d6da3280015"),
                            Menuid = "ht01",
                            Nhomky_id = new Guid("543d485d-8810-406c-9438-9fded201eeeb"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("7df6b49b-9ad5-4c34-aeee-cec98054efbc"),
                            Menuid = "ht02",
                            Nhomky_id = new Guid("543d485d-8810-406c-9438-9fded201eeeb"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("05a775d1-c823-4e5c-8e46-66597cc5f5e6"),
                            Menuid = "ht03",
                            Nhomky_id = new Guid("543d485d-8810-406c-9438-9fded201eeeb"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("4ff66c35-0e60-4442-ad73-82e695126ca4"),
                            Menuid = "ht04",
                            Nhomky_id = new Guid("543d485d-8810-406c-9438-9fded201eeeb"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("a6a189d3-5a22-469b-a300-c3f369d0f67f"),
                            Menuid = "ht05",
                            Nhomky_id = new Guid("543d485d-8810-406c-9438-9fded201eeeb"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("52f28ee0-94ba-42ce-a5c4-33e37751be85"),
                            Menuid = "ht06",
                            Nhomky_id = new Guid("543d485d-8810-406c-9438-9fded201eeeb"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        },
                        new
                        {
                            Id = new Guid("f7c7db8b-8042-459c-83dc-9e5f98deccb3"),
                            Menuid = "ht07",
                            Nhomky_id = new Guid("543d485d-8810-406c-9438-9fded201eeeb"),
                            quyenCapNhap = false,
                            quyenThem = false,
                            quyenXem = false,
                            quyenXoa = false
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys009", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manhanvien")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<Guid>("Nhomky_id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tennhomky")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thutu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nhomky_id");

                    b.HasIndex("UserID");

                    b.ToTable("UserNhomKy");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5969008c-e0d5-42d8-8b05-57468fba9817"),
                            Manhanvien = "890801",
                            Nhomky_id = new Guid("543d485d-8810-406c-9438-9fded201eeeb"),
                            Tennhomky = "Quản trị",
                            Thutu = 0,
                            Trangthai = 1,
                            UserID = new Guid("41ab7842-584d-4da5-9b38-64d71b0978cd"),
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Timer", b =>
                {
                    b.Property<int>("Timerid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Thoigiandangxuat")
                        .HasColumnType("int");

                    b.Property<byte>("Trangthai")
                        .HasColumnType("tinyint");

                    b.HasKey("Timerid");

                    b.ToTable("Timers");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys003", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys005", "Sys005")
                        .WithMany("Sys003")
                        .HasForeignKey("Danhmucid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys003")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys006", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys005", "Sys005")
                        .WithMany("Sys006")
                        .HasForeignKey("Danhmucid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys007", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys004", "Sys004")
                        .WithMany("Sys007")
                        .HasForeignKey("Groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys003", "Sys003")
                        .WithMany()
                        .HasForeignKey("Sys003Id");
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys008", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys006", "Sys006")
                        .WithMany("Sys008")
                        .HasForeignKey("Menuid");

                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys008")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppCore.Data.Entities.System.Sys009", b =>
                {
                    b.HasOne("AppCore.Data.Entities.System.Sys002", "Sys002")
                        .WithMany("Sys009")
                        .HasForeignKey("Nhomky_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCore.Data.Entities.System.Sys001", "Sys001")
                        .WithMany("Sys009")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
